image: golang:1.9-alpine

stages:
  - build
  # TODO: add tests and a test stage
  - sync
  - release

build:
  stage: build
  script:
    - cp -r `pwd` $GOPATH/src/special-log-generator
    - cd $GOPATH/src/special-log-generator
    - go build
  except:
    - tags

sync:
  stage: sync
  image: alpine
  variables:
    GIT_STRATEGY: clone
  script:
    - apk --update add git
     # We need ssh-agent to safely inject the private key (see https://docs.gitlab.com/ee/ci/ssh_keys/README.html#ssh-keys-when-using-the-docker-executor)
    - 'which ssh-agent || (apk add --no-cache openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add /dev/stdin
    - mkdir -p ~/.ssh
    # The following line disables host key checking
    # A more secure version could have all the cluster pubkeys in a variable and enable host key checking here
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git push --mirror ${GITHUB_REMOTE}
  only:
    - master

.release-template: &release-template
  stage: release
  variables:
    EXTENSION: ""
  artifacts:
    untracked: true
    name: "slg-${CI_COMMIT_REF_NAME}-${GOOS}-${GOARCH}"
  script:
    - cp -r `pwd` $GOPATH/src/special-log-generator
    - cd $GOPATH/src/special-log-generator
    - go build
    - cp special-log-generator${EXTENSION} ${CI_PROJECT_DIR}/special-log-generator${EXTENSION}
  only:
    - tags

release-linux-amd64:
  <<: *release-template
  variables:
    GOOS: linux
    GOARCH: amd64
    EXTENSION: ""
release-linux-x86:
  <<: *release-template
  variables:
    GOOS: linux
    GOARCH: "386"
    EXTENSION: ""
release-linux-arm:
  <<: *release-template
  variables:
    GOOS: linux
    GOARCH: arm
    EXTENSION: ""
release-linux-arm64:
  <<: *release-template
  variables:
    GOOS: linux
    GOARCH: arm64
    EXTENSION: ""
release-mac-amd64:
  <<: *release-template
  variables:
    GOOS: darwin
    GOARCH: amd64
    EXTENSION: ""
release-mac-x86:
  <<: *release-template
  variables:
    GOOS: darwin
    GOARCH: "386"
    EXTENSION: ""
release-windows-amd64:
  <<: *release-template
  variables:
    GOOS: windows
    GOARCH: amd64
    EXTENSION: .exe
release-windows-x86:
  <<: *release-template
  variables:
    GOOS: windows
    GOARCH: "386"
    EXTENSION: .exe
